<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sewa_model extends CI_Model
{

    public $table = 'sewa';
    public $id = 'id_sewa';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id_sewa,id_member,id_user,tgl_sewa,tgl_kembali,tgl_pengembalian,denda,total_bayar,status');
        $this->datatables->from('sewa');
        //add this line for join
        //$this->datatables->join('table2', 'sewa.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('sewa/read/$1'), '<i class="fa fa-search"></i>', 'class="btn btn-xs btn-primary"  data-toggle="tooltip" title="Detail"') . "  " . anchor(site_url('sewa/update/$1'), '<i class="fa fa-edit"></i>', 'class="btn btn-xs btn-warning" data-toggle="tooltip" title="Edit"') . "  " . anchor(site_url('sewa/delete/$1'), '<i class="fa fa-trash"></i>', 'class="btn btn-xs btn-danger" onclick="return confirmdelete(\'sewa/delete/$1\')" data-toggle="tooltip" title="Delete"'), 'id_sewa');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_sewa', $q);
        $this->db->or_like('id_member', $q);
        $this->db->or_like('id_user', $q);
        $this->db->or_like('tgl_sewa', $q);
        $this->db->or_like('tgl_kembali', $q);
        $this->db->or_like('tgl_pengembalian', $q);
        $this->db->or_like('denda', $q);
        $this->db->or_like('total_bayar', $q);
        $this->db->or_like('status', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_sewa', $q);
        $this->db->or_like('id_member', $q);
        $this->db->or_like('id_user', $q);
        $this->db->or_like('tgl_sewa', $q);
        $this->db->or_like('tgl_kembali', $q);
        $this->db->or_like('tgl_pengembalian', $q);
        $this->db->or_like('denda', $q);
        $this->db->or_like('total_bayar', $q);
        $this->db->or_like('status', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        $insert_id = $this->db->insert_id();
        return $insert_id;
    }

    function total_sewa()
    {
        $query = $this->db->query('SELECT * FROM sewa');
        return $query->num_rows();
    }
    function total_pendapatan()
    {
        $query = $this->db->query('SELECT sum(total_bayar) as pendapatan FROM sewa')->row();
        return $query->pendapatan;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
}

/* End of file Sewa_model.php */
/* Location: ./application/models/Sewa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-19 03:44:18 */
/* http://harviacode.com */